version: '2'

services:
  Insync-app:
    image: futurist2001/rpi-insync:latest
    container_name: insync-app
    environment:
      - ZABBIX_HOSTNAME=insync-app
      - INSYNC1_USERNAME=youremail
      - INSYNC1_AUTH_CODE=12345
      - INSYNC_DOWNLOAD=link
    volumes:
      - ./data:/data
      - ./config:/root/.config/Insync
    restart: always
